# ~/.tmuxinator/default.yml

name: default
root: ~/dev/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

windows:
  - vim:
      layout: b77c,209x59,0,0[209x46,0,0,0,209x12,0,47{104x12,0,47,2,104x12,105,47,3}]
      panes:
        - vim --servername default
        - pry
        -
  - server:
      layout: d79f,209x59,0,0[209x46,0,0{104x46,0,0,10,104x46,105,0,16},209x12,0,47{104x12,0,47,13,104x12,105,47,14}]
      panes:
        -
        -
        -
        - zeus start
